name: sciqis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - numpy
  - scipy
  - matplotlib
  - qutip
  - pennylane
  - strawberryfields
  - cvxpy
  - jupyter
  - jupyterlab
  - jupytext
  - notebook
  - jupyterlab_widgets
  - jupyterlab-git
  - tqdm
  - imagemagick
  - pip:
    - qutip-qip
