name: sciqis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - xeus-python
  - pip
  - numpy
  - scipy
  - matplotlib
  - qutip
  - pennylane
  - strawberryfields
  - cvxpy
  - h5py
  - jupyter
  - jupyterlab=4.0  # 4.1 breaks jupyterlab-deck
  - jupytext
  - jupyterlab-deck
  - notebook
  - jupyterlab_widgets
  - jupyterlab-git
  - tqdm
  - imagemagick
  - pip:
    - qutip-qip
