name: sciqis
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - scipy
  - matplotlib
  - conda-forge::qutip
  - conda-forge::pennylane
  - conda-forge::strawberryfields
  - conda-forge::cvxpy
  - jupyter
  - jupyterlab
  - jupytext
  - notebook
  - jupyterlab_widgets
  - jupyterlab-git
  - tqdm
  - imagemagick
  - pip:
    - qutip-qip
